services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: infobus_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for Celery and Channels
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web App (Daphne ASGI server)
  web:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    env_file:
      - .env        # Base configuration
      - .env.dev    # Development overrides (tracked)
      - .env.local  # Personal secrets and local overrides (git-ignored)
    environment:
      # Docker-specific environment variables that override env_file values if needed
      - DB_HOST=db  # Docker service name
      - REDIS_HOST=redis  # Docker service name
      # Development optimizations for hot reload
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered
      - PYTHONDONTWRITEBYTECODE=1  # Prevent Python from writing .pyc files
      - WATCHDOG_POLLING=True  # Force polling for file changes (better for Docker volumes)
    volumes:
      - .:/app  # Mount current directory for live development
      - /app/.venv  # Exclude .venv directory to prevent conflicts
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["/app/docker-entrypoint.sh"]
    command:
      [
        "uv",
        "run",
        "python",
        "manage.py",
        "runserver",
        "0.0.0.0:8000"
      ]

  # Celery Worker
  celery-worker:
    build:
      context: .
      target: development  # Use development target for hot reload
    env_file:
      - .env        # Base configuration
      - .env.dev    # Development overrides (tracked)
      - .env.local  # Personal secrets and local overrides (git-ignored)
    environment:
      # Docker-specific environment variables
      - DB_HOST=db  # Docker service name
      - REDIS_HOST=redis  # Docker service name
      # Development optimizations for hot reload
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app  # Mount source code for hot reload
      - /app/.venv  # Exclude .venv directory to prevent conflicts
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    entrypoint: ["/app/docker-entrypoint.sh"]
    command:
      [
        "uv", "run", "watchmedo", "auto-restart",
        "--patterns=*.py",
        "--recursive", "--",
        "celery", "-A", "infobus_data", "worker", "--loglevel=info"
      ]

  # Celery Beat (Scheduler)
  celery-beat:
    build:
      context: .
      target: development  # Use development target for hot reload
    env_file:
      - .env        # Base configuration
      - .env.dev    # Development overrides (tracked)
      - .env.local  # Personal secrets and local overrides (git-ignored)
    environment:
      # Docker-specific environment variables
      - DB_HOST=db  # Docker service name
      - REDIS_HOST=redis  # Docker service name
      # Development optimizations for hot reload
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - .:/app  # Mount source code for hot reload
      - /app/.venv  # Exclude .venv directory to prevent conflicts
      - celery_beat_data:/app/celerybeat-schedule
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started
    entrypoint: ["/app/docker-entrypoint.sh"]
    command:
      [
        "uv",
        "run",
        "celery",
        "-A",
        "infobus_data",
        "beat",
        "--loglevel=info",
        "--scheduler=django_celery_beat.schedulers:DatabaseScheduler",
      ]

  # Nginx (Optional - for production static file serving)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/static:ro
      - media_volume:/var/www/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  celery_beat_data:

networks:
  default:
    name: infobus_network
